# Duration-based testing configuration
[endpoint]
base_url = "http://10.3.0.1:8080/v1"
model = "gpt-3.5-turbo"
timeout = 30

[load]
concurrent_requests = 16
duration_seconds = 60  # Run for 60 seconds

[input]
file = "examples/prompts/openorca-10000.jsonl"

[output]
format = "console"

[log]
level = "info"

# Optional: Enable high-resolution metrics capture
# [metrics]
# output = "metrics.parquet"
# interval = "1s"
