# Fixed QPS with duration limit
[endpoint]
base_url = "http://localhost:8080/v1"
model = "gpt-3.5-turbo"
timeout = 30

[load]
qps = 10.0  # 10 requests per second
concurrent_requests = 20  # Max in-flight requests
duration_seconds = 30  # Run for 30 seconds

[input]
file = "examples/prompts/openorca-10000.jsonl"

[output]
format = "console"
quiet = false

[log]
level = "info"
# Optional: Enable high-resolution metrics capture
# [metrics]
# output = "metrics.parquet"
# interval = "1s"
